version: 0.0
os: linux

files:
  - source: scripts/
    destination: /home/ec2-user/scripts/
  - source: image_tag.txt
    destination: /home/ec2-user/
    overwrite: true

hooks:
  ApplicationStop:
    - location: scripts/stop_container.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_container.sh
      timeout: 300
      runas: root
